# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='avatar',
            field=models.ImageField(default='avatars/no_avatar.jpg', upload_to='avatars/'),
        ),
    ]
