# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0002_director_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'permissions': (('can_delete', 'can delete director'),)},
        ),
        migrations.AlterField(
            model_name='director',
            name='avatar',
            field=models.ImageField(default='avatars/no_avatar.jpg', upload_to='avatars'),
        ),
    ]
