# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0003_auto_20161128_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'permissions': (('can_delete', 'my can delete director'),)},
        ),
    ]
