# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0004_auto_20161128_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'permissions': (('can_delete', 'my_perm for deleting  director'),)},
        ),
    ]
